---
title: "Список лекций"
---

Здесь будет размещаться список презентаций и видеозаписей.

Лекция 1. Введение в R.

-   [Слайды](lecture1.qmd).

-   [Запись](https://drive.google.com/drive/folders/1yJvMjnJbLjYiStoRcBMN5DPSs9ooJzOc?usp=drive_link).

Лекция 2. Разбор селекционного примера с помощью линейной модели (`lm`) в R и сравнение выводов с Доспеховым.

-   [Слайды](https://github.com/ubogoeva/stats_for_plants/blob/master/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F_2_%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F.pdf)

-   [Скрипт](https://github.com/ubogoeva/stats_for_plants/blob/master/lm_factor_analysis.R) (при переходе на страницу нажмите на "download raw file" в правом верхнем углу)

-   [Данные](https://github.com/ubogoeva/stats_for_plants/raw/master/Wheat_density_terms.xlsx)

-   [Запись](https://drive.google.com/drive/folders/1UMScd2PCxN9ddSdvPQgwzJTYDnp9lgOF)

Лекция 3. Типы переменных и шкал, понятие генеральной совокупности и выборки, описательная статистика и статистика вывода - в чем разница.

-   [Слайды](lecture3.qmd).

-   [Запись](https://drive.google.com/drive/folders/1uZ7gHeIdHJN0mOE0c5RCWs4NM76LCVfB).

-   Про пределы погрешностей -- [статья](https://ubogoeva.github.io/R4Analytics/posts/types_of_error_bars.html).

-   [Скрипт](https://github.com/ubogoeva/stats_for_plants/blob/master/lesson3_variance_calc.R) и [данные](https://github.com/ubogoeva/stats_for_plants/raw/master/data/ANOVA%20single%20location%20EPBA6.xlsx).

Лекция 4. Визуализация данных с помощью [`ggplot2`](https://ggplot2.tidyverse.org/)

Лекция 5. Что такое p-value, нормальное распределение, t-распределение, тест Стьюдента. Мощность тестов (?).

Лекция 6. Простая линейная регрессия, множественная линейная регрессия.

Лекция 7. Однофакторный и многофакторный дисперсионный анализ (ANOVA).

Лекция 8. Тест Стьюдента, ANOVA и линейная регрессия как частные случаи общей линейной модели. Введение в обобщенную линейную модель.

Лекция 9. Применение статистических методов в селекции растений.

Лекция 10-11 to be confirmed

Лекция 12. Пакет [metan](https://github.com/TiagoOlivoto/metan) для расчета индексов стабильности на основе AMMI и построения GGE биплота для графического отображения взаимодействия генотип-среда.
